### ISSUE TITLE
Model Inference: Molecular weight

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-self-service#10]
### Model

Molecular weight - eos3b5e

### Molecules

CCCCOCCCC
CCCCCCC

**Comment by miquelduranfrigola** [comment]
@DhanshreeA can you check that this worked as expected? It looks good to me

**Comment by DhanshreeA** [comment]
Yep this worked as expected @miquelduranfrigola!

**Comment by miquelduranfrigola** [comment]
Awesome!
