### ISSUE TITLE
Using models from Docker

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-self-service#12]
Models are currently fetched `--from_github`. It would be much better if we fetch `--from_dockerhub`. @DhanshreeA can you take care of modifying this in the corresponding workflow file and making sure that everything works as expected?

**Comment by DhanshreeA** [comment]
Addressed in https://github.com/ersilia-os/ersilia-self-service/commit/42f6fab4fbd48553993bf3ec88f732159a1f097f
