### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Melogmo** [ersilia-os/ersilia-self-service#19]
### Model

ESKAPE pathogen inhibition - eos5xng

### Molecules

O=CC1=C(C2=C(C)C=C1O)OC3=C(O)C4=C(C(C)=C3OC2=O)COC4=O
O=C1N2C(N(C)C3=C1N=CN3C4OC(CO)C(O)C4O)=NC(C)=C2

**Comment by GemmaTuron** [comment]
and @jmassardo this is weird because it is failing with the same docker+http error as #22 but I did manage to run it yesterday with the same model successfully, see #14
