### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Melogmo** [ersilia-os/ersilia-self-service#20]
### Model

Anti-schistosomiasis activity - eos2l0q

### Molecules

O=C1N2C(N(C)C3=C1N=CN3C4OC(CO)C(O)C4O)=NC(C)=C2
O=CC1=C(C2=C(C)C=C1O)OC3=C(O)C4=C(C(C)=C3OC2=O)COC4=O

**Comment by GemmaTuron** [comment]
Hi @Melogmo 

We are testing out what might be happening. See issue #21 - we'll figure it out!
