### ISSUE TITLE
Model Inference: eos2l0q 22.05.2024

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia-self-service#21]
### Model

Anti-schistosomiasis activity - eos2l0q

### Molecules

O=C1N2C(N(C)C3=C1N=CN3C4OC(CO)C(O)C4O)=NC(C)=C2
O=CC1=C(C2=C(C)C=C1O)OC3=C(O)C4=C(C(C)=C3OC2=O)COC4=O

**Comment by GemmaTuron** [comment]
@jmassardo 

Can you help here? it seems the model name is not being well recognised at fetching time, it should only get the eos id but gets some other things?

```
Run MODEL_ID=$(echo '{"model":{"title":"Model","content":["Anti-schistosomiasis activity - eos2l0q"],"text":"Anti-schistosomiasis activity - eos2l0q"},"molecules":{"title":"Molecules","content":["O=C1N2C(N(C)C3=C1N=CN3C4OC(CO)C(O)C4O)=NC(C)=C2\r\nO=CC1=C(C2=C(C)C=C1O)OC3=C(O)C4=C(C(C)=C3OC2=O)COC4=O"],"text":"O=C1N2C(N(C)C3=C1N=CN3C4OC(CO)C(O)C4O)=NC(C)=C2\r\nO=CC1=C(C2=C(C)C=C1O)OC3=C(O)C4=C(C(C)=C3OC2=O)COC4=O"}}' | jq -r '.model.text' | cut -d'-' -f2-)
Usage: ersilia fetch [OPTIONS] MODEL
Try 'ersilia fetch --help' for help.

Error: Got unexpected extra arguments (activity - eos2l0q)
```

**Comment by jmassardo** [comment]
There's two dashes in that title and the workflow only understands one.

Here's the [line of code](https://github.com/ersilia-os/ersilia-self-service/blob/main/.github/workflows/self-service.yml#L30) that's handling that bit. Let me see of I can figure a better way to do the splitting.

**Comment by GemmaTuron** [comment]
I thought this might be the case! Do you have an easy fix @jmassardo? Many thanks for the swift response!
