### ISSUE TITLE
Update title of model inference requests

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-self-service#52]
Within the action, we should update the title so that they are homogeneous across runs. One option would be something like this:

🚀  Model Inference Run 🤖 eos3b5e: Molecular Weight 📅 2024-08-19

Therefore, we should not use the title provided by the user or, ideally, we should not allow users to enter a title.

**Comment by DhanshreeA** [comment]
Fixed here: https://github.com/ersilia-os/ersilia-self-service/commit/37dab46d8f6ca498991473d70adae36924b5a274. Eg: https://github.com/ersilia-os/ersilia-self-service/issues/58
